name: Deploy to Apache

on:
 push:
  branches:
   - master

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set execute permissions for the script
     run: |
      chmod +x ./likeme_test/deploy.sh

   - name: Run deployment script
     run: |
      bash ./likeme_test/deploy.sh
     env:
      NODE_ENV: production
