name: Deploy to Apache

on:
 push:
  branches:
   - master

jobs:
 deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: List contents of likeme_test directory
     run: |
      ls -l ./ 

   - name: Set execute permissions for the script
     run: |
      chmod +x ./deploy.sh

   - name: Run deployment script
     run: |
      bash ./deploy.sh
     env:
      NODE_ENV: production
