jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa piks.in >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Start SSH Agent
        run: eval "$(ssh-agent -s)"

      - name: Add SSH key
        run: |
          ssh-add ~/.ssh/id_rsa || exit 0

      - name: Debug SSH Connection
        run: ssh -T git@piks.in

      - name: Set execute permissions for the script
        run: chmod +x ./deploy.sh

      - name: Run deployment script
        run: |
          bash ./deploy.sh
        env:
          NODE_ENV: production
