name: Deploy to Apache

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug SSH_PRIVATE_KEY
        run: echo "$SSH_PRIVATE_KEY"

      - name: Debug SSH Key Content
        run: cat ~/.ssh/id_rsa

      - name: Start SSH Agent and Add Key
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa


      - name: Debug SSH Configuration
        run: cat ~/.ssh/config

      - name: Debug SSH Key Content
        run: cat ~/.ssh/id_rsa

      - name: Debug Known Hosts
        run: cat ~/.ssh/known_hosts

      - name: Set execute permissions for the script
        run: chmod +x ./deploy.sh

      - name: SSH to server for debugging
        run: ssh -i ~/.ssh/id_rsa root@piks.in

      - name: Run deployment script
        run: bash ./deploy.sh
        env:
          NODE_ENV: production
