name: Deploy to Apache

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set execute permissions for the script
        run: |
          chmod +x ./deploy.sh

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan piks.in >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH connection
        run: |
          ssh -T -v -i ~/.ssh/id_rsa root@piks.in

      - name: Run deployment script
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@piks.in "bash -s" < ./deploy.sh
        env:
          NODE_ENV: production
